### ISSUE TITLE
呵呵

### ISSUE THREAD

**Issue by xunyao4dev** [cheezcharmer/chinese-dictatorship#1]
只想说去尼玛的，中国人怎么你了？傻逼玩意

**Comment by JiqiangLiu** [comment]
借楼，sb帖子，已举报。满纸污言秽语、恶臭难耐。如果你信基督，那一定是从地狱爬出来的。

**Comment by cwww3** [comment]
> 借楼，sb

**Comment by magnetocoin** [comment]
naah. gonna do it on github. and not getting out of china.

**Comment by cheezcharmer** [comment]
naah. gonna do it on github. and not getting out of china.
