### ISSUE TITLE
智障东西

### ISSUE THREAD

**Issue by ty1972873004** [cheezcharmer/chinese-dictatorship#5]
外国人的狗杂种，相信你目前还在中国（包含港澳台）的土地上，有种就滚去其他地方，没种就跑这喷粪？

**Comment by cheezcharmer** [comment]
naah

**Comment by ty1972873004** [comment]
> naah

I think about why you wrote this. Maybe your entire family of women was raped by the Chinese, or your parents died

**Comment by cheezcharmer** [comment]
> > naah
> 
> I think about why you wrote this. Maybe your entire family of women was raped by the Chinese, or your parents died

what else is xi ping ping other than murdering chinese and drinking cum everyday
![Tank_Man](https://user-images.githubusercontent.com/33333749/197155770-0aac2ebc-366a-4898-8bd1-d6b81327a5d0.jpg)
